# Building and Pushing Container Images to Docker Hub

name: dockerhub-workflow

on:
  push:
    tags:
      - '*'
    branches: none
  pull_request:
    branches: [ main ]
    types:
      - closed

  schedule:
    - cron: "0 16 * * SUN" # Run every Sunday at 16:00 PM UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CACHE_NUMBER: 1  # increase to reset cache manually
  IMAGE_NAME: emotion-detection-app

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            label: Build and Push to Docker Hub
            
    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-WeekNo%U')"

      - name: Get tag
        id: repository
        run: echo "tag=$(git describe --tags --always)" > $GITHUB_ENV

      - name: Docker Hub Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          #tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.tag }}
          #tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}
          #tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          tags: ${{secrets.DOCKER_USER}}/${{env.IMAGE_NAME}}:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max

          
